disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - todo
  - vertical_whitespace
  - function_parameter_count
  - inclusive_language

excluded:
  - .build
  - Source/GIGLibraryTests

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 800

identifier_name:
  excluded:
    - InfoDictionary

large_tuple:
  warning: 3
  error: 4
