disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - todo
  - vertical_whitespace
  - function_parameter_count
  - inclusive_language
  - identifier_name

excluded:
  - .build
  - Tests

type_body_length:
  warning: 600
  error: 800

file_length:
  warning: 600
  error: 800

large_tuple:
  warning: 3
  error: 4
